USE DATABASE TEST_ADK;
USE SCHEMA ELOQUANT;

CREATE OR ALTER TABLE ELOQUANT_3035(
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    AGE NUMBER
);

ALTER TABLE ELOQUANT_3035
    MODIFY COLUMN FIRST_NAME
    SET TAG MONITORING_LMG.FIRST_NAME = 'High';


ALTER TABLE ELOQUANT_3035
    MODIFY COLUMN LAST_NAME
    SET TAG MONITORING_LMG.LAST_NAME = 'High';