USE DATABASE TEST_ADK;

USE SCHEMA TOOLKIT;

CALL CREATE_MASKING_POLICYdev(
    'ELOQUANT_FIRST_NAME',
    'STRING',
    'MONITORING_LMG.FIRST_NAME',
    'High',
    'ACCOUNTADMIN',
    '***',
    'ELOQUANT'
);

ALTER TABLE ELOQUANT.ELOQUANT_3035
  MODIFY COLUMN FIRST_NAME
  SET MASKING POLICY ELOQUANT.ELOQUANT_FIRST_NAME;

    